apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-eco
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: >-
      (event.matches('^(pull_request)$') ||
      (event.matches('^(push)$'))
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/satyamburhade/pac-demo/refs/heads/main/pipeline.yaml"
    pipelinesascode.tekton.dev/task: "../task.yaml"
# spec:
#   pipelineSpec:
#     tasks:
#       - name: echo-hello
#         taskSpec:
#           steps:
#             - name: echo
#               image: registry.access.redhat.com/ubi9/ubi-micro
#               script: |
#                 #!/usr/bin/env bash
#                 echo "hello world"
#   serviceAccountName: pipeline
