apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-eco
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: >-
      (event.matches('^(pull_request)$') && target_branch.matches("refs/heads/*") ||
      (event.matches('^(push)$') && target_branch.startsWith("refs/tags/v"))
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                #!/usr/bin/env bash
                echo "hello world"
  serviceAccountName: pipeline
