apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: test-eco
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/satyamburhade/pac-demo/refs/heads/main/pipeline.yaml"
    pipelinesascode.tekton.dev/task: "./task.yaml"
spec:
  pipelineRef:
    name: new-pipeline
#   pipelineSpec:
#     tasks:
#       - name: echo-hello
#         taskSpec:
#           steps:
#             - name: echo
#               image: registry.access.redhat.com/ubi9/ubi-micro
#               script: |
#                 #!/usr/bin/env bash
#                 echo "hello world"
#   serviceAccountName: pipeline
