apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    pipelinesascode.tekton.dev/task: "sleep"
  name: new-pipeline
spec:
  tasks:
    - name: sleep
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: sleep
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
