apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  # annotations:
  #   pipelinesascode.tekton.dev/task: "sleep"
  name: new-pipeline
spec:
  tasks:
    - name: sleep
      taskRef:
        kind: Task
        name: sleep
